spring:
  application:
    name: notification
    version: 1.0
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tripply
  mail:
    host: smtp.gmail.com
    port: 587
    username: abc@ongraph.com
    password: lzfz ywke xoms ajge
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8087
  servlet:
    context-path: /notification

application:
  notification:
    base-url: http://NOTIFICATION
  booking:
    base-url: http://BOOKING
  auth:
    base-url: http://AUTH
  ui:
    base-url: http://localhost:3000

#swagger-url: http://localhost:8087/notification/swagger-ui/index.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost