spring:
  application:
    name: notification
    version: 1.0
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tripply
  mail:
    host: smtp.gmail.com
    port: 587
    username: abc@ongraph.com
    password: lzfz ywke xoms ajge
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8087
  servlet:
    context-path: /notification

application:
  notification:
    base-url: http://localhost:8087
  booking:
    base-url: http://localhost:8085
  auth:
    base-url: http://localhost:8082

#swagger-url: http://localhost:8087/notification/swagger-ui/index.html
