spring:
  application:
    name: notification
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tripply
  mail:
    host: smtp.gmail.com
    port: 587
    username: jatin.suthar@ongraph.com
    password: lzfz ywke xoms ajge
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8087
  servlet:
    context-path: /notification

application:
  ui:
    base-url: http://localhost:3000
  auth:
      base-url: http://localhost:8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
